// <auto-generated />
using System;
using MOM3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MOM3.Migrations
{
    [DbContext(typeof(Mom3DbContext))]
    partial class Mom3DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("MOM3.Models.BookModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookGenre")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GenreModelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GenreModelId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("MOM3.Models.GenreModel", b =>
                {
                    b.Property<int>("GenreModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GenreName")
                        .HasColumnType("TEXT");

                    b.HasKey("GenreModelId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("MOM3.Models.BookModel", b =>
                {
                    b.HasOne("MOM3.Models.GenreModel", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreModelId");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("MOM3.Models.GenreModel", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
